"""new

Revision ID: 207b908ed08f
Revises: 7cc14a50001a
Create Date: 2024-07-04 15:18:08.212625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207b908ed08f'
down_revision: Union[str, None] = '7cc14a50001a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('some_index', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('first_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('enrollment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('major', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('student_id', name='students_pkey')
    )
    op.create_index('some_index', 'students', ['student_id', 'date_of_birth'], unique=False)
    # ### end Alembic commands ###
